# Generated by Django 2.2.2 on 2019-06-30 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'currencies',
            },
        ),
        migrations.CreateModel(
            name='Uf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
                ('currency', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='indicator.Currency')),
            ],
            options={
                'verbose_name_plural': 'uefes',
            },
        ),
        migrations.CreateModel(
            name='Dolar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
                ('currency', models.ForeignKey(default='2', on_delete=django.db.models.deletion.CASCADE, to='indicator.Currency')),
            ],
            options={
                'verbose_name_plural': 'uefes',
            },
        ),
    ]
